version: '3.8'

services:
  web:
    build: .
    image: alijoumaa/fast-vault:latest
    container_name: fastapi_app
    restart: always
    ports:
      - "8003:8001"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@94.130.105.162:2003/postgres
      LOG_LEVEL: "info"  # Set the logging level
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", "--workers", "4", "--timeout-keep-alive", "120"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"  # Limit log file size to 10 MB
        max-file: "3"    # Keep at most 3 log files
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health/status"]
      interval: 30s       # Check every 30 seconds
      timeout: 10s        # Time out after 10 seconds
      retries: 3          # Consider the container unhealthy after 3 failures
      start_period: 40s   # Wait 40 seconds before starting health checks
