version: '3.8'

services:
  fastapi_app:
    image: alijoumaa/fast-vault:latest
    ports:
      - "8003:8001"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
