version: '3.8'

services:
  web:
    build: .
    image: alijoumaa/fast-vault:latest
    container_name: fastapi_app
    restart: always
    ports:
      - "8003:8001"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres  # Update to reference the 'db' service
      LOG_LEVEL: "info"  # Set the logging level
    depends_on:
      - db  # Ensure the database service starts before the web service
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", "--workers", "4", "--timeout-keep-alive", "120"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"  # Limit log file size to 10 MB
        max-file: "3"    # Keep at most 3 log files
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
    driver: local
