version: '3.8'

services:
  web:
    build: .
    image: alijoumaa/fast-vault:latest
    container_name: fastapi_app
    restart: always
    ports:
      - "8003:8001"
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@94.130.105.162:2002/postgres
      LOG_LEVEL: "info"  # Set the logging level
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", "--workers", "4", "--timeout-keep-alive", "120"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"  # Limit log file size to 10 MB
        max-file: "3"    # Keep at most 3 log files