"""changed synthetic data table

Revision ID: 6163a4f8d1ca
Revises: d88148386e1d
Create Date: 2024-08-22 10:51:03.601968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6163a4f8d1ca'
down_revision: Union[str, None] = 'd88148386e1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('synthetic_data', sa.Column('original_data_ids', sa.Text(), nullable=True))
    op.drop_constraint('synthetic_data_original_data_id_fkey', 'synthetic_data', type_='foreignkey')
    op.drop_column('synthetic_data', 'original_data_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('synthetic_data', sa.Column('original_data_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('synthetic_data_original_data_id_fkey', 'synthetic_data', 'data_records', ['original_data_id'], ['id'])
    op.drop_column('synthetic_data', 'original_data_ids')
    # ### end Alembic commands ###
