"""first_migration

Revision ID: 81ee08529b4c
Revises: 
Create Date: 2024-09-04 14:45:41.970340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ee08529b4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synthetic_data_titanic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('synthesizer_type', sa.String(), nullable=True),
    sa.Column('data', sa.String(), nullable=True),
    sa.Column('original_data_ids', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synthetic_data_titanic_id'), 'synthetic_data_titanic', ['id'], unique=False)
    op.create_index(op.f('ix_synthetic_data_titanic_synthesizer_type'), 'synthetic_data_titanic', ['synthesizer_type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_synthetic_data_titanic_synthesizer_type'), table_name='synthetic_data_titanic')
    op.drop_index(op.f('ix_synthetic_data_titanic_id'), table_name='synthetic_data_titanic')
    op.drop_table('synthetic_data_titanic')
    # ### end Alembic commands ###
