"""add new data format

Revision ID: b1138cb5cf50
Revises: 6163a4f8d1ca
Create Date: 2024-08-22 16:33:44.298913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1138cb5cf50'
down_revision: Union[str, None] = '6163a4f8d1ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_synthetic_data_id', table_name='synthetic_data')
    op.drop_index('ix_synthetic_data_synthesizer_type', table_name='synthetic_data')
    op.drop_table('synthetic_data')
    op.drop_index('ix_data_record_credit_card_id', table_name='data_record_credit_card')
    op.drop_table('data_record_credit_card')
    op.drop_index('ix_data_records_id', table_name='data_records')
    op.drop_table('data_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('arrival_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('efficiency', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('leaving_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='data_records_pkey')
    )
    op.create_index('ix_data_records_id', 'data_records', ['id'], unique=False)
    op.create_table('data_record_credit_card',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('v1', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('v2', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('v3', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='data_record_credit_card_pkey')
    )
    op.create_index('ix_data_record_credit_card_id', 'data_record_credit_card', ['id'], unique=False)
    op.create_table('synthetic_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('synthesizer_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('original_data_ids', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='synthetic_data_pkey')
    )
    op.create_index('ix_synthetic_data_synthesizer_type', 'synthetic_data', ['synthesizer_type'], unique=False)
    op.create_index('ix_synthetic_data_id', 'synthetic_data', ['id'], unique=False)
    # ### end Alembic commands ###
