"""added foreign id from synthetic data to original data

Revision ID: d88148386e1d
Revises: dcc34b904255
Create Date: 2024-08-21 16:21:06.958778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd88148386e1d'
down_revision: Union[str, None] = 'dcc34b904255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('synthetic_data', sa.Column('original_data_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'synthetic_data', 'data_records', ['original_data_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'synthetic_data', type_='foreignkey')
    op.drop_column('synthetic_data', 'original_data_id')
    # ### end Alembic commands ###
